services:
  loki:
    container_name: loki
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - monitoring
  promtail:
    container_name: promtail 
    image: grafana/promtail
    volumes:
      - './loki/promtail-config.yaml:/etc/promtail/promtail-config.yaml'
      - '/var/log/containers:/var/log/containers:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers:ro'
      - '/var/log:/var/log:ro'
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - monitoring
  cadvisor:
    image: zcube/cadvisor
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    networks:
      - monitoring
  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: on-failure
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - '/:/host:ro,rslave'
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - prome_data:/var/lib/prometheus
    networks:
      - monitoring
    depends_on:
      - cadvisor
      - node_exporter 
    ports:
      - "9090:9090"
    restart: on-failure
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    depends_on:
     - prometheus
    restart: on-failure

volumes:
  prome_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge